name: Validate

on: 
  push:
    branches: [ 'main', 'v[0-9]+', 'v[0-9]+.[0-9]+' ]
    tags-ignore: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/flutter-validate.yml@4ffc79239063f81ec576e90a6bdbd179f8999430
